### ISSUE TITLE
The post you are trying to reply to does not appear to exist.

### ISSUE THREAD

**Issue by cadusilva** [cadusilva/bolha-clima#10]
Todas as consultas ao bot agora passaram a produzir o seguinte erro:

``` python
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 
'The post you are trying to reply to does not appear to exist.')
```

Não importa a privacidade do post com a consulta, o erro é o mesmo. Testei a partir do Mastodon da Bolhinha e do GoToSocial. Erro completo:

``` python
Traceback (most recent call last):
  File "/opt/gitwork/clima/under_the_weather.py", line 188, in <module>
    main()
  File "/opt/gitwork/clima/under_the_weather.py", line 179, in main
    mastodon.stream_user(listener=StreamListenerWeather(mastodon))
  File "/usr/local/lib/python3.11/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mastodon/utility.py", line 49, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mastodon/streaming_endpoints.py", line 21, in stream_user
    return self.__stream('/api/v1/streaming/user', listener, run_async=run_async, timeout=timeout, reconnect_async=reconnect_async, reconnect_async_wait_sec=reconnect_async_wait_sec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mastodon/internals.py", line 540, in __stream
    listener.handle_stream(r)
  File "/usr/local/lib/python3.11/dist-packages/mastodon/streaming.py", line 125, in handle_stream
    self._dispatch(event)
  File "/usr/local/lib/python3.11/dist-packages/mastodon/streaming.py", line 224, in _dispatch
    handler(payload)
  File "/opt/gitwork/clima/under_the_weather.py", line 132, in on_notification
    self.mastodon.status_post(
  File "/usr/local/lib/python3.11/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mastodon/utility.py", line 49, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mastodon/statuses.py", line 248, in status_post
    return self.__status_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mastodon/statuses.py", line 182, in __status_internal
    return self.__api_request('POST', '/api/v1/statuses', params, headers=headers, use_json=use_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mastodon/internals.py", line 297, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'The post you are trying to reply to does not appear to exist.')
```

Acontece tanto dentro de uma imagem Docker quanto fora.

**Comment by cadusilva** [comment]
Ah, o bot em seguida quebra e é encerrado.

**Comment by cadusilva** [comment]
Descobri o problema: a requisição ficava presa no buffer do proxy reverso do nginx. Desativei isso e resolveu.
