### ISSUE TITLE
mastodon.errors.MastodonVersionError: Version check failed (Need version 1.1.1)

### ISSUE THREAD

**Issue by cadusilva** [cadusilva/bolha-clima#3]
Durante a madrugada ocorreram esses erros. Será que foi alguma instabilidade no servidor da instância ou um problema no próprio bot?

<details>
<summary>Muitas linhas de log</summary>

```
Nov 16 00:53:28 services python3[66247]: Toot foi favoritado por @focarafa
Nov 16 01:08:03 services python3[66247]: Traceback (most recent call last):
Nov 16 01:08:03 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/urllib3/response.py", line 761, in _update_chunk_length
Nov 16 01:08:03 services python3[66247]:     self.chunk_left = int(line, 16)
Nov 16 01:08:03 services python3[66247]:                       ^^^^^^^^^^^^^
Nov 16 01:08:03 services python3[66247]: ValueError: invalid literal for int() with base 16: b''
Nov 16 01:08:03 services python3[66247]: During handling of the above exception, another exception occurred:
Nov 16 01:08:03 services python3[66247]: Traceback (most recent call last):
Nov 16 01:08:03 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/urllib3/response.py", line 444, in _error_catcher
Nov 16 01:08:03 services python3[66247]:     yield
Nov 16 01:08:03 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/urllib3/response.py", line 828, in read_chunked
Nov 16 01:08:03 services python3[66247]:     self._update_chunk_length()
Nov 16 01:08:03 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/urllib3/response.py", line 765, in _update_chunk_length
Nov 16 01:08:03 services python3[66247]:     raise InvalidChunkLength(self, line)
Nov 16 01:08:03 services python3[66247]: urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)
Nov 16 01:08:03 services python3[66247]: During handling of the above exception, another exception occurred:
Nov 16 01:08:03 services python3[66247]: Traceback (most recent call last):
Nov 16 01:08:03 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/requests/models.py", line 816, in generate
Nov 16 01:08:04 services python3[66247]:     yield from self.raw.stream(chunk_size, decode_content=True)
Nov 16 01:08:04 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/urllib3/response.py", line 624, in stream
Nov 16 01:08:04 services python3[66247]:     for line in self.read_chunked(amt, decode_content=decode_content):
Nov 16 01:08:04 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/urllib3/response.py", line 816, in read_chunked
Nov 16 01:08:04 services python3[66247]:     with self._error_catcher():
Nov 16 01:08:04 services python3[66247]:   File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
Nov 16 01:08:04 services python3[66247]:     self.gen.throw(typ, value, traceback)
Nov 16 01:08:04 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/urllib3/response.py", line 461, in _error_catcher
Nov 16 01:08:04 services python3[66247]:     raise ProtocolError("Connection broken: %r" % e, e)
Nov 16 01:08:04 services python3[66247]: urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
Nov 16 01:08:04 services python3[66247]: During handling of the above exception, another exception occurred:
Nov 16 01:08:04 services python3[66247]: Traceback (most recent call last):
Nov 16 01:08:04 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/mastodon/streaming.py", line 109, in handle_stream
Nov 16 01:08:04 services python3[66247]:     for chunk in response.iter_content(chunk_size=1):
Nov 16 01:08:04 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/requests/models.py", line 818, in generate
Nov 16 01:08:04 services python3[66247]:     raise ChunkedEncodingError(e)
Nov 16 01:08:04 services python3[66247]: requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
Nov 16 01:08:04 services python3[66247]: The above exception was the direct cause of the following exception:
Nov 16 01:08:04 services python3[66247]: Traceback (most recent call last):
Nov 16 01:08:04 services python3[66247]:   File "/opt/clima/under_the_weather.py", line 147, in <module>
Nov 16 01:08:04 services python3[66247]:     main()
Nov 16 01:08:04 services python3[66247]:   File "/opt/clima/under_the_weather.py", line 138, in main
Nov 16 01:08:04 services python3[66247]:     mastodon.stream_user(listener=StreamListenerWeather(mastodon))
Nov 16 01:08:04 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/decorator.py", line 232, in fun
Nov 16 01:08:04 services python3[66247]:     return caller(func, *(extras + args), **kw)
Nov 16 01:08:04 services python3[66247]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 16 01:08:04 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/mastodon/utility.py", line 49, in wrapper
Nov 16 01:08:04 services python3[66247]:     return function(self, *args, **kwargs)
Nov 16 01:08:04 services python3[66247]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 16 01:08:04 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/mastodon/streaming_endpoints.py", line 21, in stream_user
Nov 16 01:08:04 services python3[66247]:     return self.__stream('/api/v1/streaming/user', listener, run_async=run_async, timeout=timeout, reconnect_async=reconnect_async, reconnect_async_wait_sec=reconnect_>
Nov 16 01:08:04 services python3[66247]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^>
Nov 16 01:08:04 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/mastodon/internals.py", line 540, in __stream
Nov 16 01:08:04 services python3[66247]:     listener.handle_stream(r)
Nov 16 01:08:04 services python3[66247]:   File "/usr/local/lib/python3.11/dist-packages/mastodon/streaming.py", line 135, in handle_stream
Nov 16 01:08:04 services python3[66247]:     six.raise_from(
Nov 16 01:08:04 services python3[66247]:   File "<string>", line 3, in raise_from
Nov 16 01:08:04 services python3[66247]: mastodon.errors.MastodonNetworkError: Server ceased communication.
Nov 16 01:08:04 services systemd[1]: clima.service: Main process exited, code=exited, status=1/FAILURE
Nov 16 01:08:04 services systemd[1]: clima.service: Failed with result 'exit-code'.
Nov 16 01:08:04 services systemd[1]: clima.service: Consumed 1.460s CPU time.
Nov 16 01:08:05 services systemd[1]: clima.service: Scheduled restart job, restart counter is at 1.
Nov 16 01:08:05 services systemd[1]: Stopped clima.service - Bot Bolha Clima.
Nov 16 01:08:05 services systemd[1]: clima.service: Consumed 1.460s CPU time.
Nov 16 01:08:05 services systemd[1]: Started clima.service - Bot Bolha Clima.
Nov 16 01:08:06 services python3[67855]: Traceback (most recent call last):
Nov 16 01:08:06 services python3[67855]:   File "/opt/clima/under_the_weather.py", line 147, in <module>
Nov 16 01:08:06 services python3[67855]:     main()
Nov 16 01:08:06 services python3[67855]:   File "/opt/clima/under_the_weather.py", line 135, in main
Nov 16 01:08:06 services python3[67855]:     mastodon.account_update_credentials(note=os.getenv("MASTODON_BIO_ONLINE"))
Nov 16 01:08:06 services python3[67855]:   File "/usr/local/lib/python3.11/dist-packages/decorator.py", line 232, in fun
Nov 16 01:08:06 services python3[67855]:     return caller(func, *(extras + args), **kw)
Nov 16 01:08:06 services python3[67855]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 16 01:08:06 services python3[67855]:   File "/usr/local/lib/python3.11/dist-packages/mastodon/utility.py", line 46, in wrapper
Nov 16 01:08:06 services python3[67855]:     raise MastodonVersionError(f"Version check failed (Need version {version})")
Nov 16 01:08:06 services python3[67855]: mastodon.errors.MastodonVersionError: Version check failed (Need version 1.1.1)
Nov 16 01:08:06 services systemd[1]: clima.service: Main process exited, code=exited, status=1/FAILURE
Nov 16 01:08:06 services systemd[1]: clima.service: Failed with result 'exit-code'.
Nov 16 01:08:07 services systemd[1]: clima.service: Scheduled restart job, restart counter is at 2.
Nov 16 01:08:07 services systemd[1]: Stopped clima.service - Bot Bolha Clima.
Nov 16 01:08:07 services systemd[1]: Started clima.service - Bot Bolha Clima.
Nov 16 01:08:07 services python3[67859]: Traceback (most recent call last):
Nov 16 01:08:07 services python3[67859]:   File "/opt/clima/under_the_weather.py", line 147, in <module>
Nov 16 01:08:07 services python3[67859]:     main()
Nov 16 01:08:07 services python3[67859]:   File "/opt/clima/under_the_weather.py", line 135, in main
Nov 16 01:08:07 services python3[67859]:     mastodon.account_update_credentials(note=os.getenv("MASTODON_BIO_ONLINE"))
Nov 16 01:08:07 services python3[67859]:   File "/usr/local/lib/python3.11/dist-packages/decorator.py", line 232, in fun
Nov 16 01:08:07 services python3[67859]:     return caller(func, *(extras + args), **kw)
Nov 16 01:08:07 services python3[67859]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 16 01:08:07 services python3[67859]:   File "/usr/local/lib/python3.11/dist-packages/mastodon/utility.py", line 46, in wrapper
Nov 16 01:08:07 services python3[67859]:     raise MastodonVersionError(f"Version check failed (Need version {version})")
Nov 16 01:08:07 services python3[67859]: mastodon.errors.MastodonVersionError: Version check failed (Need version 1.1.1)
Nov 16 01:08:07 services systemd[1]: clima.service: Main process exited, code=exited, status=1/FAILURE
Nov 16 01:08:07 services systemd[1]: clima.service: Failed with result 'exit-code'.
Nov 16 01:08:08 services systemd[1]: clima.service: Scheduled restart job, restart counter is at 3.
Nov 16 01:08:08 services systemd[1]: Stopped clima.service - Bot Bolha Clima.
Nov 16 01:08:08 services systemd[1]: Started clima.service - Bot Bolha Clima.
Nov 16 01:08:08 services python3[67862]: Traceback (most recent call last):
Nov 16 01:08:08 services python3[67862]:   File "/opt/clima/under_the_weather.py", line 147, in <module>
Nov 16 01:08:08 services python3[67862]:     main()
Nov 16 01:08:08 services python3[67862]:   File "/opt/clima/under_the_weather.py", line 135, in main
Nov 16 01:08:08 services python3[67862]:     mastodon.account_update_credentials(note=os.getenv("MASTODON_BIO_ONLINE"))
Nov 16 01:08:08 services python3[67862]:   File "/usr/local/lib/python3.11/dist-packages/decorator.py", line 232, in fun
Nov 16 01:08:08 services python3[67862]:     return caller(func, *(extras + args), **kw)
Nov 16 01:08:08 services python3[67862]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 16 01:08:08 services python3[67862]:   File "/usr/local/lib/python3.11/dist-packages/mastodon/utility.py", line 46, in wrapper
Nov 16 01:08:08 services python3[67862]:     raise MastodonVersionError(f"Version check failed (Need version {version})")
Nov 16 01:08:08 services python3[67862]: mastodon.errors.MastodonVersionError: Version check failed (Need version 1.1.1)
Nov 16 01:08:09 services systemd[1]: clima.service: Main process exited, code=exited, status=1/FAILURE
Nov 16 01:08:09 services systemd[1]: clima.service: Failed with result 'exit-code'.
Nov 16 01:08:09 services systemd[1]: clima.service: Scheduled restart job, restart counter is at 4.
Nov 16 01:08:09 services systemd[1]: Stopped clima.service - Bot Bolha Clima.
Nov 16 01:08:09 services systemd[1]: Started clima.service - Bot Bolha Clima.
Nov 16 01:08:10 services python3[67865]: Traceback (most recent call last):
Nov 16 01:08:10 services python3[67865]:   File "/opt/clima/under_the_weather.py", line 147, in <module>
Nov 16 01:08:10 services python3[67865]:     main()
Nov 16 01:08:10 services python3[67865]:   File "/opt/clima/under_the_weather.py", line 135, in main
Nov 16 01:08:10 services python3[67865]:     mastodon.account_update_credentials(note=os.getenv("MASTODON_BIO_ONLINE"))
Nov 16 01:08:10 services python3[67865]:   File "/usr/local/lib/python3.11/dist-packages/decorator.py", line 232, in fun
Nov 16 01:08:10 services python3[67865]:     return caller(func, *(extras + args), **kw)
Nov 16 01:08:10 services python3[67865]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 16 01:08:10 services python3[67865]:   File "/usr/local/lib/python3.11/dist-packages/mastodon/utility.py", line 46, in wrapper
Nov 16 01:08:10 services python3[67865]:     raise MastodonVersionError(f"Version check failed (Need version {version})")
Nov 16 01:08:10 services python3[67865]: mastodon.errors.MastodonVersionError: Version check failed (Need version 1.1.1)
Nov 16 01:08:10 services systemd[1]: clima.service: Main process exited, code=exited, status=1/FAILURE
Nov 16 01:08:10 services systemd[1]: clima.service: Failed with result 'exit-code'.
Nov 16 01:08:10 services systemd[1]: clima.service: Scheduled restart job, restart counter is at 5.
Nov 16 01:08:10 services systemd[1]: Stopped clima.service - Bot Bolha Clima.
Nov 16 01:08:10 services systemd[1]: Started clima.service - Bot Bolha Clima.
Nov 16 01:08:11 services python3[67868]: Traceback (most recent call last):
Nov 16 01:08:11 services python3[67868]:   File "/opt/clima/under_the_weather.py", line 147, in <module>
Nov 16 01:08:11 services python3[67868]:     main()
Nov 16 01:08:11 services python3[67868]:   File "/opt/clima/under_the_weather.py", line 135, in main
Nov 16 01:08:11 services python3[67868]:     mastodon.account_update_credentials(note=os.getenv("MASTODON_BIO_ONLINE"))
Nov 16 01:08:11 services python3[67868]:   File "/usr/local/lib/python3.11/dist-packages/decorator.py", line 232, in fun
Nov 16 01:08:11 services python3[67868]:     return caller(func, *(extras + args), **kw)
Nov 16 01:08:11 services python3[67868]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 16 01:08:11 services python3[67868]:   File "/usr/local/lib/python3.11/dist-packages/mastodon/utility.py", line 46, in wrapper
Nov 16 01:08:11 services python3[67868]:     raise MastodonVersionError(f"Version check failed (Need version {version})")
Nov 16 01:08:11 services python3[67868]: mastodon.errors.MastodonVersionError: Version check failed (Need version 1.1.1)
Nov 16 01:08:11 services systemd[1]: clima.service: Main process exited, code=exited, status=1/FAILURE
Nov 16 01:08:11 services systemd[1]: clima.service: Failed with result 'exit-code'.
Nov 16 01:08:11 services systemd[1]: clima.service: Scheduled restart job, restart counter is at 6.
Nov 16 01:08:11 services systemd[1]: Stopped clima.service - Bot Bolha Clima.
Nov 16 01:08:11 services systemd[1]: clima.service: Start request repeated too quickly.
Nov 16 01:08:11 services systemd[1]: clima.service: Failed with result 'exit-code'.
Nov 16 01:08:11 services systemd[1]: Failed to start clima.service - Bot Bolha Clima.
Nov 16 09:00:17 services systemd[1]: Started clima.service - Bot Bolha Clima.
```
</details>

**Comment by cadusilva** [comment]
Olhei aqui e não houve queda de internet que gerasse uma rediscagem, mas 01h da madrugada é um horário de estresse no servidor por conta das rotinas de backup.

**Comment by ghost** [comment]
O log apresenta uma exceção lançada pela biblioteca Mastodon.py

> mastodon.errors.MastodonNetworkError: Server ceased communication.

Encontrei [essa issue](https://github.com/halcy/Mastodon.py/issues/243) no upstream sugerindo que a exceção é causada por uma falha (temporária?) na instância do mastodon. Diante dessa falha a aplicação cliente que executa no bot não tem nada a fazer a não ser lançar uma exceção.

Como este parece um problema intermitente e o serviço do systemd já se encarrega de reiniciar o bot após uma falha, sugiro apenas aumentarmos o tempo de espera entre tentativas consecutivas de restart.

```
...  
[Service]  
RestartSec=1  
...
```

Caso o problema volte a acontecer ou esta solução gere novos impactos, podemos alternativamente implementar um exponential backoff no código.

**Comment by cadusilva** [comment]
Obrigado @nandavereda, vou fechar o issue e caso necessário reabrimos ele!
